- name: Template Docker daemon config
  ansible.builtin.copy:
    content: "{{ docker['daemon.json'] | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart Docker

- name: Create directory for Docker service overrides
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Template Docker service overrides
  tags: skip_ansible_lint
  ansible.builtin.copy:
    content: |
      #jinja2: trim_blocks: False
      [Service]
      {%- for var, val in docker.daemon_environment.items() %}
      Environment={{ var }}={{ val }}
      {%- endfor %}
    dest: /etc/systemd/system/docker.service.d/ansible.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart Docker
