- name: Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems)
  ansible.builtin.apt:
    update_cache: yes
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  ansible.builtin.apt:
    update_cache: yes
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '>=')

- name: Add Docker apt key
  ansible.builtin.get_url:
    url: "{{ docker.repository.key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker.repository.apt }}"
    state: present
    update_cache: true

- name: Install Docker, docker-compose and pigz
  block:
    - name: Attempt installation
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.apt:
        name:
          - docker-ce
          - python3
          - python3-pip
          - docker-ce-cli
          - docker-ce-rootless-extras
          - containerd.io
          - pigz
  rescue:
    - name: Fix the Ubuntu Jammy error
      ansible.builtin.replace:
        path: /etc/systemd/system/multi-user.target.wants/docker.service
        regexp: "fd://"
        replace: "unix://"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.04', '>=')

- name: Install python modules
  block:
    - name: Install python modules (pip)
      ansible.builtin.apt:
        update_cache: yes
        name:
          - requests
          - 'urllib3<2'
          - docker
  rescue:
    - name: Install python modules (apt)
      ansible.builtin.pip:
        name:
          - python3-requests
          - python3-urllib3
          - python3-docker

- name: Enable and start Docker
  ansible.builtin.systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: started
