- name: Install Docker, docker-compose and pigz
  apt:
    name:
      - docker.io
      - docker-compose
      - pigz

- name: Enable and start Docker
  systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: started
