- name: Install docker
  ansible.builtin.include_tasks: install.yaml

- name: Configure docker
  ansible.builtin.include_tasks: config.yaml

- name: Configure DNS for docker
  ansible.builtin.include_tasks: dns.yaml
