- name: Install docker
  ansible.builtin.import_tasks: install.yaml

- name: Configure docker
  ansible.builtin.import_tasks: config.yaml

- name: Configure DNS for docker
  ansible.builtin.import_tasks: dns.yaml
