- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart docker-systemd-resolved-proxy
  when: not docker_systemd_resolved_proxy_start_result.changed
  ansible.builtin.systemd:
    name: docker-systemd-resolved-proxy
    state: restarted
