---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Run hello-world container
      community.docker.docker_container:
        name: hello-world
        image: hello-world
        state: started

    - name: Stop hello-world container
      community.docker.docker_container:
        name: hello-world
        image: hello-world
        state: stopped

    - name: Create a folder for a docker-compose stack
      ansible.builtin.file:
        state: directory
        path: /var/opt/compose
        recurse: yes

    - name: Template an example docker-compose stack
      ansible.builtin.copy:
        content: |
          services:
            hello_world:
              image: hello-world
        dest: /var/opt/compose/docker-compose.yml
        mode: "0644"
        owner: root
        group: root

    - name: Start the docker-compose stack
      register: docker_compose_up_result
      changed_when: yes
      ansible.builtin.command:
        cmd: docker-compose up
        chdir: /var/opt/compose

    - name: Show the docker-compose up result
      ansible.builtin.debug:
        var: docker_compose_up_result.stdout
