---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check docker CLI is installed
      changed_when: false
      ansible.builtin.command: docker --version

    - name: Check dockerd binary is installed
      changed_when: false
      ansible.builtin.command: dockerd --version

    - name: Get service facts
      ansible.builtin.service_facts:

    - name: Check docker service is enabled and active
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].status == 'enabled'
          - ansible_facts.services['docker.service'].state == 'running'

    - name: Check docker-systemd-resolved-proxy service is enabled and active
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker-systemd-resolved-proxy.service'].status == 'enabled'
          - ansible_facts.services['docker-systemd-resolved-proxy.service'].state == 'running'
