---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check docker CLI is installed
      changed_when: false
      ansible.builtin.shell: command -v docker

    - name: Check dockerd binary is installed
      changed_when: false
      ansible.builtin.shell: command -v dockerd

    - name: Check docker service is enabled
      changed_when: false
      ansible.builtin.command: systemctl is-enabled docker

    - name: Check docker service is active
      changed_when: false
      ansible.builtin.command: systemctl is-active docker

    - name: Check docker-systemd-resolved-proxy service is enabled
      changed_when: false
      ansible.builtin.command: systemctl is-enabled docker-systemd-resolved-proxy

    - name: Check docker-systemd-resolved-proxy service is active
      changed_when: false
      ansible.builtin.command: systemctl is-active docker-systemd-resolved-proxy
